### ISSUE TITLE
v2023.11.0~1で使えない

### ISSUE THREAD

**Issue by tamaina** [misskey-dev/summerflare#3]
という話を聞いた

**Comment by acid-chicken** [comment]
再現しないが

**Comment by fu-sen** [comment]
別に issues を建てても良いかもしれませんが、Firefish で試したところレスポンスがないように見えました。バージョンとかではない別の条件で動いていない可能性がありそうです。

**Comment by acid-chicken** [comment]
レスポンスがない、とは

**Comment by Srgr0** [comment]
``https://summaly.arkjp.net``から移行する場合、``https://hoge.hoge/url``で登録する(パスとしてurlを入れる)必要があって、そこで躓いている可能性がありそう。~~自分がそうだった~~

**Comment by fu-sen** [comment]
> レスポンスがない、とは

URL 入りの投稿をしても下に何も展開されません。

**Comment by fu-sen** [comment]
> `https://summaly.arkjp.net`から移行する場合、`https://hoge.hoge/url`で登録する(パスとしてurlを入れる)必要があって、そこで躓いている可能性がありそう。~自分がそうだった~

https://github.com/misskey-dev/summerflare/blob/master/src/index.ts#L26

あ～これですね。これははまるケースが多いとみました。
よく見ると README の Usage に記載があるのですが、そもそもの URL の意味と混同しますね……

**Comment by fu-sen** [comment]
ビルドして、 `https://●●●.●●●..workers.dev/url` での動作を確認できました。自分は解決ですが、上記のとおり、このままだとはまる人が出てくると思うので、検討を要するかと思います。

Edit: 追記: `https://独自ドメイン/url` も正常動作を確認できています。

**Comment by ikasoba** [comment]
僕は開発版のmisskeyに追従してるみすてむずというサーバーの住人です。
みすてむずではsummerflareを使っているらしいですが、埋め込みが一部表示されないという細かいバグがある程度でその他はバッチリに見えました。
埋め込みについては #2 として修正のPRを出してみました。
前回のレビュー確認後修正いたしましたのでまたご確認していただけると嬉しいです。
